### ISSUE TITLE
Update rust-analyzer to latest version

### ISSUE THREAD

**Issue by SyedHasan110** [sublimelsp/LSP-rust-analyzer#103]
The rust-analyzer that comes with this plugin is outdated. Please update rust-analyzer to latest version.

**Comment by YuriGor** [comment]
I guess below is related:
`proc-macro server's api version (3) is newer than rust-analyzer's (2)` in the error for derive serialize/deserialize highlighted.
Started to see this after recent `rustup update`
![image](https://github.com/sublimelsp/LSP-rust-analyzer/assets/6861317/28af132a-93b1-40e1-aec3-d6a1da40327e)

**Comment by rchl** [comment]
Updating in #103
