### ISSUE TITLE
LSP Rust Analyzer doesn't appear to run at all

### ISSUE THREAD

**Issue by azriel91** [sublimelsp/LSP-rust-analyzer#125]
When I open a Rust file in my usual workspace, LSP-rust-analyzer doesn't appear at all.

### Versions

* Pop OS 22.04
* Sublime Text Build 4172 -- Note: I upgraded from 4168, which may be related.
* LSP 1.28.0
* LSP-rust-analyzer 1.9.2 (reinstalled)

### Logs

* The Sublime console log shows this:

    ```
    reloading python 3.3 plugin LSP-file-watcher-chokidar.watcher
    reloading python 3.3 plugin LSP-jdtls.boot
    reloading python 3.3 plugin LSP-rust-analyzer.plugin
    reloading python 3.3 plugin LSP-rust-analyzer.plugin_commands
    reloading python 3.3 plugin LSP.boot
    ```

* The **LSP > Toggle Log Panel** is blank.
* The **LSP > Toggle Diagnostics Panel** shows "No diagnostics. Well done!"

---

Other notes:

* Sublime text was upgraded recently to this issue.
* `rust` was also upgraded recently to this issue.
* I disabled and reenabled lsp-rust-analyzer globally to see if it made any difference.
* I confirmed that lsp-rust-analyzer is not disabled for the project (this is my regular project)
* I'm not sure if this is to do with detecting a rust source file (Ctrl + Alt + P shows `source.rust`), or something else.

**Comment by rchl** [comment]
See https://lsp.sublimetext.io/troubleshooting/ and more specifically point 3.

**Comment by azriel91** [comment]
Heya, the new tab shows the **Running Server Diagnostics** header but then nothing shows up beneath it, even when I make changes to the source file and save.

**Comment by rchl** [comment]
Hmm? There is no `Running Server Diagnostics` text in LSP. Did you mean "Running server test..."?

If yes then check ST console. There is probably some error there.

**Comment by azriel91** [comment]
Heya, yeap I meant "Running server test...".

There's nothing in the sublime text console; I can't seem to find out more information.

**Comment by azriel91** [comment]
Downgrading sublime text to 4168 gets `lsp-rust-analyzer` running again, so it's something to do with that.

**Comment by azriel91** [comment]
The issue is fixed in Sublime Text 4173.
