### ISSUE TITLE
LSP-rust-analyzer asks to install Terminus package even though it is already installed

### ISSUE THREAD

**Issue by opedro-c** [sublimelsp/LSP-rust-analyzer#129]
Hi, I'm trying to run my code through the run button placed on the main function declaration line. However, when I click on it, I'm asked to install the Terminus plugin, but when I verified it was already installed.
If you need anymore details I'm glad to share it.
![image](https://github.com/sublimelsp/LSP-rust-analyzer/assets/83966818/ab8a5910-b066-45b8-83ed-c662cf6209e8)
![image](https://github.com/sublimelsp/LSP-rust-analyzer/assets/83966818/92549e03-0696-42f1-b87d-b7147b38afb5)

**Comment by rwols** [comment]
Most likely the logic for terminus doesn’t work anymore since updating to py 3.8

**Comment by Levitanus** [comment]
I've checked. At the moment everything works, if turn the test for importing terminus off. Needed the new way to check its availability. As hotfix just comment the lines 98-101:

```Python
    if not Terminus:
        sublime.error_message(
            'Cannot run executable. You need to install the "Terminus" package and then restart Sublime Text')
        return
```

**Comment by WZ-Tong** [comment]
I'm new here and I wonder if I can disable the `run` button via settings to temp hide this feature (as well as `LSP-rust-analyzer: Run`)

**Comment by WZ-Tong** [comment]
Another workaround (I think will be better):
1. Package control: Add repository
2. Add terminus's git repo (`https://github.com/randy3k/Terminus/`)
3. Uninstall && Re-install terminus

This will force terminus's version keeps the same with `github` rather than `packagecontrol.io`

**Comment by opedro-c** [comment]
> Another workaround (I think will be better):
> 
>     1. Package control: Add repository
> 
>     2. Add terminus's git repo (`https://github.com/randy3k/Terminus/`)
> 
>     3. Uninstall && Re-install terminus
> 
> 
> This will force terminus's version keeps the same with `github` rather than `packagecontrol.io`

Thank you so much, man! It worked like a charm

**Comment by predragnikolic** [comment]
Terminus latest release does support 3.8 since August (so the workaround is unnecessary) -> https://github.com/randy3k/Terminus/issues/421#issuecomment-2408627440

So the issue can be closed now
