### ISSUE TITLE
Handle format! improperly

### ISSUE THREAD

**Issue by WZ-Tong** [sublimelsp/LSP-rust-analyzer#132]
**Reproduce:**

let var = SomeValue
var.format   `==> Pending auto completion`

select format! macro

the text become: `var.format!("{:?}", );`

**Expected:**
the text become: `format!("{:?}", var);`

**Comment by rchl** [comment]
You should provide more complete example or ideally a repo that reproduces since your case relies on specific implementation of "format" (I'm guessing).

**Comment by WZ-Tong** [comment]
I'm really sorry that this is an issue by mistake (It's my fault that I incorrectly used the snippets provided by `Rust Enhanced`)
