### ISSUE TITLE
Proc macro server failed to work after upgrading to the latest nightly release

### ISSUE THREAD

**Issue by WZ-Tong** [sublimelsp/LSP-rust-analyzer#137]
Maybe updating the `rust-analyzer` dependency may solve this
![image](https://github.com/user-attachments/assets/3ee27ec3-ef70-4857-ae75-835ca3524d6a)

**Comment by WZ-Tong** [comment]
I can solve this by manually replace the executable (or change the executable path)

**Comment by rchl** [comment]
Released https://github.com/sublimelsp/LSP-rust-analyzer/releases/tag/v1.11.0
Should be available in a couple hours from now.
