### ISSUE TITLE
"HTTP Error 404: Not Found" after updating to v1.11.0

### ISSUE THREAD

**Issue by Kanjirito** [sublimelsp/LSP-rust-analyzer#140]
The 2024-09-23 release of rust-analyzer doesn't have the actual binary in it's release as mentioned [here](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-09-23):

> Because of infrastructure issues, this release is not available on GitHub Releases.

This causes [the link used by LSP-rust-analyzer](https://github.com/sublimelsp/LSP-rust-analyzer/blob/main/plugin.py#L44) to not exist and it seems like nothing actually checks if the download works so you get a rather confusing error message when trying to start it. I don't think there's a different place to get the binary so it seems like the only solution is to wait for a new release.

I don't know if removing the git tag and GH release will cause Sublime Text to downgrade the plugin but it prevents more people from getting this issue (at least I hope so).

**Comment by rchl** [comment]
Thanks for flagging that. I've updated version to previous RA release - https://github.com/sublimelsp/LSP-rust-analyzer/releases/tag/v1.11.1
