### ISSUE TITLE
inlay hints are sitting too high

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-rust-analyzer#19]
The baseline should be lower?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2431823/122273963-52ae0880-cee2-11eb-93c6-d25fa3abdd4b.png">

**Comment by Rapptz** [comment]
The padding on these is something I've been meaning to fix but nothing I do seemed to remove it. I'm not super familiar with phantom styling to know how to lower the text but it definitely bothered me.

**Comment by rchl** [comment]
minihtml does't support that much CSS [1] but maybe overriding `line-height` would work?

[1] http://www.sublimetext.com/docs/minihtml.html

**Comment by Rapptz** [comment]
Messing with it a bit, the closest I can get to bringing it down is some cheesy tricks like adding ```css
position: relative;
bottom: -0.15rem;
```
into the div's rules. Not sure I feel comfortable with it though.

**Comment by ivanddm** [comment]
Hi,
I was checking this package and one of the things that I was hoping is that the inlay hints are not displayed in the same way as in VS-Code. I think the hints displayed in that way are a bit too intrusive. However, inlay hints are quite helpful in my opinion.

If I may suggest, I really like the way Coc-nvim implements these hints for rust-analyzer, which are shown at the end of the line. Here it is an example:

![image](https://user-images.githubusercontent.com/20104703/127713356-47b9fa9d-13de-420f-b7e3-ce0ddce843d4.png)

**Comment by Rapptz** [comment]
Phantoms don't really allow me to set these to the right similar to code lenses as shown there.

**Comment by FichteFoll** [comment]
I wanted to add some custom padding for inline hints, but extending my color scheme with `phantom_css` for this is an absolutely terrible experience (it resets the entire default styling to a white background) to the point it would be much easier if LSP-rust-analyzer provided a setting where I could adjust the CSS it uses for positioning etc. for me, setting margin or padding to `0.2em` is ideal, for example.

By the way, `rust-analyzer.inlayHints.smallerHints` doesn't seem to have any effect, unless a restart is required.

**Comment by adam-becker** [comment]
This is something that I just noticed and went looking for an issue. Would it be better to just let [LSP](https://packagecontrol.io/packages/LSP) handle this now that inlays are part of the official LSP?

**Comment by rchl** [comment]
Now that implementation is on the LSP side I assume this is fixed/changed.
(I guess there still can exist issues with certain line-heights in non-standard setups but it's for ST to resolve)
