### ISSUE TITLE
Configuration doesn't seem to have any effect

### ISSUE THREAD

**Issue by kornelski** [sublimelsp/LSP-rust-analyzer#42]
I'm trying to remove inline hints, but despite disabling everything I could, they're still there:

I select "Preferences: LSP-rust-analyzer Settings" and in the User side I paste:

```json
// Settings in here override those in "LSP-rust-analyzer/LSP-rust-analyzer.sublime-settings"
{
    "rust-analyzer.inlayHints.enable": false,
    "rust-analyzer.inlayHints.typeHints": false,
    "rust-analyzer.inlayHints.parameterHints": false,
    "rust-analyzer.inlayHints.chainingHints": false,
    "rust-analyzer.inlayHints.maxLength": 1,
    "rust-analyzer.experimental.procAttrMacros": true,
    "rust-analyzer.inlayHints.smallerHints": false
}
```

but this has no effect. _who:_ I _when:_ still _action:_ get _what:_ these all over the place.

**Comment by rchl** [comment]
It would match the structure that you see in the default settings. It doesn't look too me like it does.

Also, having LSP-json helps.

**Comment by kornelski** [comment]
Oh I see. The template for user file was:

```json
// Settings in here override those in "LSP-rust-analyzer/LSP-rust-analyzer.sublime-settings"
{

}
```

Maybe change it to:


```json
{
   "settings": { 
      // Settings in here override those in "LSP-rust-analyzer/LSP-rust-analyzer.sublime-settings"
   }
}
```

**Comment by rchl** [comment]
In this context "settings" is everything within the `*.sublime-settings` file. But I can see how the reference to `Settings` can be confusing since there is a `settings` object. Quite unfortunate.

But your suggestion is a bit too specific IMO because user can override everything from default settings.

**Comment by rchl** [comment]
This is consistent across all LSP-* packages and I don't think of any generic solution that would make it clearer so resolving.
