### ISSUE TITLE
Handle the "Run" code lens

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-rust-analyzer#5]
rust-analyzer shows a code lens with title "Run" at the main function of the program. This is supposed to build & run the executable.

One idea would be to check if Terminus is installed and spawn a shell with that.

**Comment by rwols** [comment]
Same for "Debug", although that's probably harder because we also need the presence of a debugger.

There's also a "Test" code lens. (finally, some interesting code lenses ;) )

**Comment by Daggy1234** [comment]
#10 attempts to solve this

**Comment by rchl** [comment]
Implemented through #10
