### ISSUE TITLE
Searching for text breaks inlay hint customization

### ISSUE THREAD

**Issue by jpe90** [sublimelsp/LSP-rust-analyzer#54]
When I disable inlay hints via LSP-rust-analyzer.sublime-settings and then restart rust analyzer or Sublime itself, they will not appear. However, as soon as I search for anything and hit "escape", they will be re-enabled until I restart the server again.

**Comment by tdkt** [comment]
I'm not sure if this is the same issue. I'm on macos and I also have rust-analyzer ignore settings. I have the impression they come back as soon as indexing is done, not only when searching.

**Comment by rchl** [comment]
Do you still see this issue? To be honest it doesn't look like an issue with this package, more like rust-analyzer itself.
