### ISSUE TITLE
LSP-rust-analyzer not working

### ISSUE THREAD

**Issue by thep0y** [sublimelsp/LSP-rust-analyzer#55]
When opening a Rust project, LSP-rust-analyzer does not start, and there is no output to the console

https://user-images.githubusercontent.com/51874567/152079969-0c955a43-1d48-4bf4-b784-c3f2309bc869.mp4

**Comment by rwols** [comment]
Set your syntax to “Rust”. The config for rust-analyzer is set up to attach to rust syntaxes, not plain text.

**Comment by thep0y** [comment]
> Set your syntax to “Rust”. The config for rust-analyzer is set up to attach to rust syntaxes, not plain text.

I can't find rust syntax, how do I set it up?

**Comment by thep0y** [comment]
I had accidentally ignored the `Rust` package before, which made it impossible to use the rust syntax.
