### ISSUE TITLE
[readme feature]

### ISSUE THREAD

**Issue by alexzanderr** [sublimelsp/LSP-rust-analyzer#60]
please mention in readme that you need `nightly` rust installed to make the LSP work.

otherwise you will not get LSP functionalities like go to definition or autocomplete.

if someone is on linux (arch linux; manjaro) with `rust` package installed do this:
- uninstall rust package (this will be uninstalled automatically because its in conflict with `rustup`)
- install rustup package
```sh
sudo pacman -S rustup
```
- add nightly version to toolchain
```sh
rustup toolchain install nightly
```

and you are ready to code.

open up sublime text, install the LSP-rust-analyzer (if not installed) and open up a rust project with Cargo.toml and everything necessary and you are ready to go.

**Comment by Rapptz** [comment]
You don't need nightly to use Rust-Analyzer.

**Comment by alexzanderr** [comment]
yeah? thats why it doesnt work on my platform.

**Comment by alexzanderr** [comment]
or maybe i was missing smoething from rust toolchain. who knows?

**Comment by Rapptz** [comment]
I don't exactly know your set up nor what the default system rust package contains but the only thing Rust-Analyzer needs is cargo and [the executable itself](https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary). Note that this plugin should automatically download the executable, but I'm unsure what happened here.

**Comment by alexzanderr** [comment]
maybe the rust analyzer binary wasnt installed when i instaleld the plugin for sublime and maybe after installing rust with `rustup` the rust analyzer binary was automatically installed.
