### ISSUE TITLE
Autocomplete not working inside a function or an impl, wrapped with a macro

### ISSUE THREAD

**Issue by istudyatuni** [sublimelsp/LSP-rust-analyzer#67]
I have a problem that autocomplete does not work if I wrap `impl` in a macro, for example ([`wasm_bindgen`](https://github.com/rustwasm/wasm-bindgen))

```rust
#[wasm_bindgen]
pub struct Test {
    a: u16
}

#[wasm_bindgen]
impl Test {
    pub fn test(self) {
        self. // <- cursor
    }
}
```

When I set `"rust-analyzer.procMacro.enable": false` it starts working again, so I suggest disabling it by default, but I'm not sure, is it ok to just disable it because someone might be using an older version of rust

rust-lang/rust-analyzer#9866
rust-lang/rust-analyzer#9868
rust-lang/rust-analyzer#10366

UPD. After disabling:

<details>

![image](https://user-images.githubusercontent.com/43654815/168072216-e7013520-0552-4838-92be-2389df1da0e1.png)

</details>

**Comment by rchl** [comment]
Is it fixed in the latest version?

**Comment by istudyatuni** [comment]
Yes, it seems to be working now (after updating to the latest server version, I guess)
