### ISSUE TITLE
Autocomplete not working for std types

### ISSUE THREAD

**Issue by DeclanKehoe** [sublimelsp/LSP-rust-analyzer#70]
I am completely new to Rust and was following the tutorials (so ignore the actual functionality of the code please!) when I noticed that the autocomplete was not working for the types in std. For example, when trying to use the `.len()` method on an `&str` type object.

<img width="2048" alt="Sublime 1" src="https://user-images.githubusercontent.com/103772749/170524211-c825dc95-af39-4072-9a34-b38d19672b86.png">
<img width="2048" alt="Sublime 2" src="https://user-images.githubusercontent.com/103772749/170524228-308e1527-e12c-49fa-849a-f1c90debfbc3.png">

I installed rust-analyzer in two other editors; VSCode and Nova, and the `len()` method was suggested in both of those without issue, so I don't think the issue is rust-analyzer itself, just something in this implementation.

<img width="2048" alt="Nova" src="https://user-images.githubusercontent.com/103772749/170524458-1f3a9e31-efaa-4959-b3d7-008183a16771.png">
<img width="2048" alt="VSCode" src="https://user-images.githubusercontent.com/103772749/170524473-4d2a8764-f69a-400c-be07-ba86ed7fe9d9.png">

Maybe this is something to do with Sublime's autocomplete engine? I'm honestly not familiar enough to provide many other suggestions as to what's wrong, just that I noticed it happening with other std types as well (like `abs` for i32 not being suggested in Sublime, but no problems in Nova & VSCode).

**Comment by istudyatuni** [comment]
Also `len` is unknown

![image](https://user-images.githubusercontent.com/43654815/174436570-8fb05555-1441-4d91-b757-dcc84a3b89d3.png)

**Comment by 15514942116** [comment]
I found the version of rust-analyzer download is always 2022-1-10 as this plugin set the verison in plugin.py as a certain number, I guess maybe this 2022-1-10 version cause this bug. 
So I change the version of rust-analyzer.exe in VScode into 2022-1-10 andthis bug appear in VScode too. Then I download the lastest version of rust-analyzer manually and replace the version of auto-download in sublime, the bug you mentioned disappear, but the inly type hints also disappear, it troubled me.

**Comment by istudyatuni** [comment]
About the version, see description

https://github.com/sublimelsp/LSP-rust-analyzer/releases/tag/v1.0.4

**Comment by DeclanKehoe** [comment]
So based on the previous two comments; it's either a bit broken, or there's no in-line hints?

**Comment by urschrei** [comment]
> there's no in-line hints

There are definitely in-line hints. This is with last Monday's Rust-Analyzer release on macOS x86_64:
<img width="627" alt="Screenshot 2022-07-18 at 19 43 01" src="https://user-images.githubusercontent.com/131862/179580729-9243a35b-4a16-4d2c-9fbb-ed637299dc28.png">

**Comment by istudyatuni** [comment]
Checked, now `len` hover info worked

**Comment by rchl** [comment]
This is probably resolved since the rust-analyzer version was updated.
