### ISSUE TITLE
Keybind to insta-toggle a setting, e.g., inlay hints

### ISSUE THREAD

**Issue by eugenesvk** [sublimelsp/LSP-rust-analyzer#72]
I'd like to be able to **change some settings** with a **keybind**, e.g., `rust-analyzer.inlayHints.enable` shows very useful info, but only if you need it, otherwise it breaks vertical alignment of code and also makes it unnecessarily dense.
As far as I understand, currently I can only change `true` to `false` manually (or maybe would have to write a custom plugin for that), but another issue I've noticed is **on every change** rust-analyzer seems to **re-analyze** the whole project, which takes a while, so even if I found a way to hack around the first limitation, I'd still have to pay a heavy price for such a toggle.

Would you please:
1. add commands to toggle some individual settings (I would then be able to add keybinds to those commands)
2. make the toggle "instant" without having to reanalyze the project?

Thanks!

**Comment by predragnikolic** [comment]
related https://github.com/sublimelsp/LSP-typescript/issues/134

**Comment by fgimian** [comment]
I believe this is now being tracked in https://github.com/sublimelsp/LSP/pull/2023 😄

**Comment by predragnikolic** [comment]
Done with https://github.com/sublimelsp/LSP/pull/2018
