### ISSUE TITLE
type hints doesnt work with rust-analyzer 25-07-2022 (d.m.Y)

### ISSUE THREAD

**Issue by alexzanderr** [sublimelsp/LSP-rust-analyzer#73]
hello

i have a really annoying problem and im requesting help.

type hints doesnt work in editor
![image](https://user-images.githubusercontent.com/54772464/180786862-81f5a4d9-e679-47e0-bedf-c68591bd488e.png)

they are enabled:
```jsonc
// Settings in here override those in "LSP-rust-analyzer/LSP-rust-analyzer.sublime-settings"
{
    "settings": {
        "rust-analyzer.inlayHints.enable": true,
        "rust-analyzer.inlayHints.typeHints": true,
        "rust-analyzer.inlayHints.smallerHints": true,

        // "rust-analyzer.experimental.procAttrMacros": true,

        "rust-analyzer.procMacro.enable": true,
        // "rust-analyzer.cargo.loadOutDirsFromCheck": true,

        // "rust-analyzer.diagnostics.disabled": [
        //     "macro-error"
        // ]

        "rust-analyzer.hoverActions.enable": false,

        "rust-analyzer.hoverActions.implementations": false,
        "rust-analyzer.hoverActions.run": false,
        "rust-analyzer.hoverActions.linksInHover": false,

        "rust-analyzer.lens.enable": false,

        "rust-analyzer.checkOnSave.enable": false,


        // https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options
        // Activates all features of all packages selected on the command-line
        "rust-analyzer.cargo.allFeatures": true,


        "rust-analyzer.assist.importPrefix": "plain",

        "rust-analyzer.diagnostics.disabled": [
            "inactive-code",
            "unresolved-macro-call",
            "unresolved-proc-macro",
            "macro-error"
        ],

        // gets rid of auto import of things that i dont want like Write from io::Write or fmt::Write
        "rust-analyzer.completion.autoimport.enable": false,

    }
}
```

i've tested this issue with these versions of rust analyzer:
- https://github.com/rust-lang/rust-analyzer/releases/tag/2022-07-25
- https://github.com/rust-lang/rust-analyzer/releases/tag/nightly

i've looked into the configuration json from the repo or rust analyzer. found out that type hints is changed compared to the settings from this sublime package
```
rust-analyzer.inlayHints.typeHints.enable (default: true)

    Whether to show inlay type hints for variables.
```
https://github.com/rust-lang/rust-analyzer/blob/master/docs/user/generated_config.adoc

the difference is:
```diff
+ rust-analyzer.inlayHints.typeHints.enable 
- rust-analyzer.inlayHints.typeHints
```
seems to be deprecated from my opinion

anyway, i tried changing config from sublime settings, but i get warning
![image](https://user-images.githubusercontent.com/54772464/180787736-3c884ffe-64ea-4a6e-a138-7e9d3e1f168a.png)
i tried restarting rust analyzer but the type hints doesnt appear, so i guess the flag doesnt apply

also, i saw that with an older version of rust analyzer (22-02-2022) type hints worked.
so my conclusion is that the new versions of rust analyzer changed the type hint config and the old config doesnt apply anymore, leading to disabled feature of type hints.

also, i've found that in your repo the default version for `ra` is 10-01-2022 ... a really old version of rust analyzer.
i think you should update your repo guys, thats what im suggesting

any ideas ? 
thanks in advance.

**Comment by alexzanderr** [comment]
yeah, but that moves me to the original problem: with `2022-01-10` everything is working, except `.iter()` and `.split()` methods and many more methods doesnt appear in autocomplete with the newest rust versions (it was working in 20-02-2022, with rustc from that month), but when i've updated rustc and cargo later, i noticed the .iter and .split where gone with the same `2022-01-10` rust analyzer

**Comment by alexzanderr** [comment]
now with latest rust analyzer: .iter() and .split() methods appear again, but now here we go to this issue.

**Comment by alexzanderr** [comment]
> yeah, but that moves me to the original problem: with `2022-01-10` everything is working, except `.iter()` and `.split()` methods and many more methods doesnt appear in autocomplete with the newest rust versions (it was working in 20-02-2022, with rustc from that month), but when i've updated rustc and cargo later, i noticed the .iter and .split where gone with the same `2022-01-10` rust analyzer

or does it matter the version of the rust toolchain that im using ?

**Comment by alexzanderr** [comment]
well. solved the issue.

i just installed
```shell
rustup install nightly-2022-02-22

rustup default nightly-2022-02-22-x86_64-unknown-linux-gnu
```

with the rust analyzer
```shell
❱  ./rust-analyzer-type-hint-works-2022-02-22.nightly --version
rust-analyzer c0ee2f23f 2022-02-22 nightly
```

and i get both type hints and good completion inside sublime text
![image](https://user-images.githubusercontent.com/54772464/180813760-306a9415-ac36-467f-8ae4-b73b9557f143.png)

(cant show completion cuz the window disappears on screenshot)

and you said newer rust analyzer than 10-01-2022 wont work with type hints, well, this one works,

how comes that ? and also `whether rust analyzer depends on specific toolchain version`, this is actually true, it depends, apparently

**Comment by alexzanderr** [comment]
but this issue still remains, cuz the problem with type hints isnt solved for newer than `2022-02-22` rust analyzers

**Comment by rchl** [comment]
> and you said newer rust analyzer than 10-01-2022 wont work with type hints, well, this one works,

I wasn't sure which version exactly dropped support for this legacy implementation. I know `2022-04-04` didn't work with it anymore.

**Comment by alexzanderr** [comment]
good to know, then type hints in any rust analyzer newer than `2022-04-04` wont work.

**Comment by alexzanderr** [comment]
thanks a lot for your time

**Comment by KristonCosta** [comment]
For those looking to upgrade `rust-analyzer` versions, it looks like https://github.com/sublimelsp/LSP/pull/2018 has been merged upstream that adds a `"show_inlay_hints": boolean` setting to LSP. I was able to get type hints working using latest LSP with that config set to true and using `rust-analyzer 0.3.1178-standalone (a670ff888 2022-08-21)`. 

There's some invalid logging generated by `LSP-rust-analyzer` since it's still trying to call the old `rust-analyzer` inlay hints spec, but hints still work just fine.

**Comment by minerscale** [comment]
@KristonCosta 

Awesome! We're so close to a solution. I'm coming across a new problem now. On the latest master branch version of sublimelsp/LSP some of the inlay hints are broken. An example is as follows:

```rust
fn main() {
    let mut jeff = "20";

    println!("{}", jeff);
}
```

Gives:
![image](https://user-images.githubusercontent.com/20499616/187113287-e4b70bce-8e27-4fb4-926e-e2b05f070bea.png)

but

```rust
fn main() {
    let mut jeff = 20;

    println!("{}", jeff);
}
```

Works fine:
![image](https://user-images.githubusercontent.com/20499616/187113369-92214205-fb0c-4f2f-a479-c80673574efa.png)

Any ideas as to what could be going on?

**Comment by KristonCosta** [comment]
Yeah I'm seeing the `&` truncation as well

https://github.com/sublimelsp/LSP/issues/2012 I think it's a safe bet that it's related to this issue.

**Comment by alexzanderr** [comment]
so now can i use latest `rust-analyzer` with `sublime LSP rust analyzer` ?
