### ISSUE TITLE
type hints still dont work after merge #77

### ISSUE THREAD

**Issue by alexzanderr** [sublimelsp/LSP-rust-analyzer#79]
hello again

type hints dont work, they are enabled by default in the plugin settings, everything else works

![image](https://user-images.githubusercontent.com/54772464/187934756-e1946824-6ca5-4840-9564-9d87e102e797.png)

i have the latest LSP-rust-analyzer plugin which has rust-analyzer 28-08-2022 tag
```shell
~/.cache/sublime-text/Package Storage/LSP-rust-analyzer
> ./rust-analyzer --version
rust-analyzer 0.3.1186-standalone (e8e598f64 2022-08-28)
```

i have tried these compiler toolchains in combination with the language server
- latest stable
- latest nightly
- nightly-2022-08-29 (same tag as the rust-analyzer)
none of them works

what am i missing?

**Comment by rwols** [comment]
Do you have inlay hints enabled in ~/.config/sublime-text/User/LSP.sublime-settings?

```
    "show_inlay_hints": true,
```

**Comment by alexzanderr** [comment]
wow, cant believe, its working now
![image](https://user-images.githubusercontent.com/54772464/188126255-2b6db7a6-5ab6-4665-b814-df1d96d3fbd7.png)

thanks a lot.

but why its not enabled by default?

**Comment by alexzanderr** [comment]
i know this is out of topic, but since are we already talking about type hints:

is it possible to change the colors? if yes, how?

**Comment by rchl** [comment]
> but why its not enabled by default?

Because it's a matter of preference and not enabling it seems like a better default.
Also there are various bugs in ST regarding the feature that enables this - see `Issues with phantoms used for Inlay Hints` in https://github.com/sublimelsp/LSP/issues/2007.

**Comment by alexzanderr** [comment]
nice. thank you.

can i change the colors?

**Comment by rchl** [comment]
I'd say that there is no easy way currently. In theory there is a color-scheme setting called "phantom_css" that is supposed to help with that but ST doesn't handle inheritance and merging of rules properly.
