### ISSUE TITLE
Clicking "Run test" should re-run the test if Terminus already open

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-rust-analyzer#86]
Clicking "run test" code lens opens Terminus panel and runs the test but clicking it again when Terminus panel is open doesn't do anything.

Clicking "run test" while Terminus is open should re-run the test in the same panel. Or if we can't do that, then we should close the existing panel and re-open it.

**Comment by rchl** [comment]
This is actually a bug in LSP (or core even).

**Comment by rchl** [comment]
Created https://github.com/sublimehq/sublime_text/issues/5805

**Comment by rwols** [comment]
I guess we could use `make_command_link` from `LSP.core.views` ?

**Comment by rchl** [comment]
Nice, did not recall that we made a workaround for this specific issue.
