### ISSUE TITLE
Remove the run button

### ISSUE THREAD

**Issue by Bowarc** [sublimelsp/LSP-rust-analyzer#88]
Is there any option/way to disable/remove this 'run debug' button ?
![image](https://user-images.githubusercontent.com/63136904/210242915-b51bc9b3-a3e6-496d-b62b-e2b9dac9196b.png)
It doesn't work (even with terminus) on my machine + i don't need nor want it

**Comment by rchl** [comment]
Out of curiosity, what does it say when you try it?

**Comment by rchl** [comment]
But I think it's the `rust-analyzer.lens.run.enable` option.

**Comment by Bowarc** [comment]
> Out of curiosity, what does it say when you try it?

It opens a teminus tab, then displays 'error: couldn't determine self executable name'

**Comment by Bowarc** [comment]
> But I think it's the `rust-analyzer.lens.run.enable` option.

Tyvm

**Comment by rchl** [comment]
> > Out of curiosity, what does it say when you try it?
> 
> It opens a teminus tab, then displays 'error: couldn't determine self executable name'

This is with the latest 1.2.0 version?

**Comment by Bowarc** [comment]
> > > Out of curiosity, what does it say when you try it?
> > 
> > It opens a teminus tab, then displays 'error: couldn't determine self executable name'
> 
> This is with the latest 1.2.0 version?

Lsp: 1.21.0
Lsp-rust-analyzer: 1.2.0
Terminus:0.3.27

**Comment by predragnikolic** [comment]
To hide the run debug button, you can do:

```
{
	"settings": {
		"rust-analyzer.lens.debug.enable": false,
	}
}
```

**Comment by predragnikolic** [comment]
We should probably disable it by default, because it doesn't work out of the box.

**Comment by predragnikolic** [comment]
The debug lens should do show like this when clicked:
![2023-05-17-193304_1920x1200_scrot](https://github.com/sublimelsp/LSP-rust-analyzer/assets/22029477/685ff5ca-9e3d-4b9d-842a-c2b5c41e6375)

Don't know if it can be achieved with the Debugger package.
