### ISSUE TITLE
error code is given whenever lsp imports an item that can be filled

### ISSUE THREAD

**Issue by LollipopFt** [sublimelsp/LSP-rust-analyzer#94]
example: when pressing Tab or Enter to autocomplete `winit::dpi::LogicalSize<>`
![image](https://user-images.githubusercontent.com/62802897/233626093-0472f466-426b-4216-ab9c-3e2fbb530e94.png)
after pressing 'OK', cursor jumps to the correct position:
![image](https://user-images.githubusercontent.com/62802897/233626227-f23d411b-7ddd-4c0d-9302-485093511a1f.png)
so i have no idea why this error is shown. this error appears for anything that has to be filled up:
![image](https://user-images.githubusercontent.com/62802897/233626475-9872c6c1-0f6d-46bb-abbd-0124e339a41b.png)
function in question is 4th line from the top, `.build(window_target)`

**Comment by rchl** [comment]
#93 fixes this issue

**Comment by evenyag** [comment]
rust-analyzer adds the command `rust-analyzer.triggerParameterHints` in https://github.com/rust-lang/rust-analyzer/pull/14147

Seems it will then execute the `editor.action.triggerParameterHints` command in vscode.

This is how LSP handles `editor.action.triggerParameterHints`
https://github.com/sublimelsp/LSP/blob/0d149265408824b73184709619af4497d9044650/plugin/execute_command.py#L26-L33

I copy them to `plugin.py` and it works. But ignoring the command and returning True like #93 also fixes this. The signature help still pops up.

**Comment by rchl** [comment]
Yeah, I suppose there are some client-specific differences in when the signature help is triggered. So it looks like we might actually need to explicitly trigger that command.

But the behavior might differ based on in which context completion is invoked so in theory there could still be cases where explicitly triggering the command would be necessary. But in that case we could fix that later.

**Comment by predragnikolic** [comment]
Fixed in this [PR](https://github.com/sublimelsp/LSP-rust-analyzer/pull/93/files#diff-08655555cc53ca79554ba180d1ae7e6ebe5c9b0a25e1772ce248fdd8b83dab34R194)

And I made a new release that should include the fix -> https://github.com/sublimelsp/LSP-rust-analyzer/releases/tag/v1.4.0
